//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.296
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportEtran.EtranParsingServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParsingResult", Namespace="http://schemas.datacontract.org/2004/07/ParsingLib")]
    [System.SerializableAttribute()]
    public partial class ParsingResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountProcessedRecordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable DataTableResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExeptionMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ExportEtran.EtranParsingServiceReference.OperationList> OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExportEtran.EtranParsingServiceReference.TableTypeList TableTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountProcessedRecords {
            get {
                return this.CountProcessedRecordsField;
            }
            set {
                if ((this.CountProcessedRecordsField.Equals(value) != true)) {
                    this.CountProcessedRecordsField = value;
                    this.RaisePropertyChanged("CountProcessedRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable DataTableResult {
            get {
                return this.DataTableResultField;
            }
            set {
                if ((object.ReferenceEquals(this.DataTableResultField, value) != true)) {
                    this.DataTableResultField = value;
                    this.RaisePropertyChanged("DataTableResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExeptionMsg {
            get {
                return this.ExeptionMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ExeptionMsgField, value) != true)) {
                    this.ExeptionMsgField = value;
                    this.RaisePropertyChanged("ExeptionMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ExportEtran.EtranParsingServiceReference.OperationList> Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((this.OperationField.Equals(value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNameField, value) != true)) {
                    this.TableNameField = value;
                    this.RaisePropertyChanged("TableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExportEtran.EtranParsingServiceReference.TableTypeList TableType {
            get {
                return this.TableTypeField;
            }
            set {
                if ((this.TableTypeField.Equals(value) != true)) {
                    this.TableTypeField = value;
                    this.RaisePropertyChanged("TableType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationList", Namespace="http://schemas.datacontract.org/2004/07/ParsingLib")]
    public enum OperationList : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        I = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        U = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        D = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableTypeList", Namespace="http://schemas.datacontract.org/2004/07/ParsingLib")]
    public enum TableTypeList : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentTable = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChildTable = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EtranParsingServiceReference.IParsingService")]
    public interface IParsingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParsingService/ParseBill", ReplyAction="http://tempuri.org/IParsingService/ParseBillResponse")]
        ExportEtran.EtranParsingServiceReference.ParsingResult[] ParseBill(System.Data.SqlClient.SqlConnection connection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParsingService/ParseVPU", ReplyAction="http://tempuri.org/IParsingService/ParseVPUResponse")]
        ExportEtran.EtranParsingServiceReference.ParsingResult[] ParseVPU(System.Data.SqlClient.SqlConnection connection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParsingService/ParseNK", ReplyAction="http://tempuri.org/IParsingService/ParseNKResponse")]
        ExportEtran.EtranParsingServiceReference.ParsingResult[] ParseNK(System.Data.SqlClient.SqlConnection connection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParsingService/ParseZ", ReplyAction="http://tempuri.org/IParsingService/ParseZResponse")]
        ExportEtran.EtranParsingServiceReference.ParsingResult[] ParseZ(System.Data.SqlClient.SqlConnection connection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParsingService/GetOperationList", ReplyAction="http://tempuri.org/IParsingService/GetOperationListResponse")]
        ExportEtran.EtranParsingServiceReference.OperationList GetOperationList();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParsingServiceChannel : ExportEtran.EtranParsingServiceReference.IParsingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParsingServiceClient : System.ServiceModel.ClientBase<ExportEtran.EtranParsingServiceReference.IParsingService>, ExportEtran.EtranParsingServiceReference.IParsingService {
        
        public ParsingServiceClient() {
        }
        
        public ParsingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParsingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParsingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParsingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExportEtran.EtranParsingServiceReference.ParsingResult[] ParseBill(System.Data.SqlClient.SqlConnection connection) {
            return base.Channel.ParseBill(connection);
        }
        
        public ExportEtran.EtranParsingServiceReference.ParsingResult[] ParseVPU(System.Data.SqlClient.SqlConnection connection) {
            return base.Channel.ParseVPU(connection);
        }
        
        public ExportEtran.EtranParsingServiceReference.ParsingResult[] ParseNK(System.Data.SqlClient.SqlConnection connection) {
            return base.Channel.ParseNK(connection);
        }
        
        public ExportEtran.EtranParsingServiceReference.ParsingResult[] ParseZ(System.Data.SqlClient.SqlConnection connection) {
            return base.Channel.ParseZ(connection);
        }
        
        public ExportEtran.EtranParsingServiceReference.OperationList GetOperationList() {
            return base.Channel.GetOperationList();
        }
    }
}
