//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Метаданные связи EDM

[assembly: EdmRelationshipAttribute("ExportEtranModel", "FK_tbl_Bill_tbl_BillCar", "tbl_BillCar", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ExportEtran.tbl_BillCar), "tbl_Bill", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExportEtran.tbl_Bill), true)]
[assembly: EdmRelationshipAttribute("ExportEtranModel", "FK_tbl_BillCar_tbl_Bill", "tbl_Bill", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ExportEtran.tbl_Bill), "tbl_BillCar", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExportEtran.tbl_BillCar), true)]

#endregion

namespace ExportEtran
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class ExportEtranEntities : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект ExportEtranEntities, используя строку соединения из раздела "ExportEtranEntities" файла конфигурации приложения.
        /// </summary>
        public ExportEtranEntities() : base("name=ExportEtranEntities", "ExportEtranEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта ExportEtranEntities.
        /// </summary>
        public ExportEtranEntities(string connectionString) : base(connectionString, "ExportEtranEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта ExportEtranEntities.
        /// </summary>
        public ExportEtranEntities(EntityConnection connection) : base(connection, "ExportEtranEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<tbl_Bill> tbl_Bill
        {
            get
            {
                if ((_tbl_Bill == null))
                {
                    _tbl_Bill = base.CreateObjectSet<tbl_Bill>("tbl_Bill");
                }
                return _tbl_Bill;
            }
        }
        private ObjectSet<tbl_Bill> _tbl_Bill;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<tbl_BillCar> tbl_BillCar
        {
            get
            {
                if ((_tbl_BillCar == null))
                {
                    _tbl_BillCar = base.CreateObjectSet<tbl_BillCar>("tbl_BillCar");
                }
                return _tbl_BillCar;
            }
        }
        private ObjectSet<tbl_BillCar> _tbl_BillCar;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<tbl_ConfRef> tbl_ConfRef
        {
            get
            {
                if ((_tbl_ConfRef == null))
                {
                    _tbl_ConfRef = base.CreateObjectSet<tbl_ConfRef>("tbl_ConfRef");
                }
                return _tbl_ConfRef;
            }
        }
        private ObjectSet<tbl_ConfRef> _tbl_ConfRef;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<vw_ConfRef> vw_ConfRef
        {
            get
            {
                if ((_vw_ConfRef == null))
                {
                    _vw_ConfRef = base.CreateObjectSet<vw_ConfRef>("vw_ConfRef");
                }
                return _vw_ConfRef;
            }
        }
        private ObjectSet<vw_ConfRef> _vw_ConfRef;

        #endregion
        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet tbl_Bill. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTotbl_Bill(tbl_Bill tbl_Bill)
        {
            base.AddObject("tbl_Bill", tbl_Bill);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet tbl_BillCar. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTotbl_BillCar(tbl_BillCar tbl_BillCar)
        {
            base.AddObject("tbl_BillCar", tbl_BillCar);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet tbl_ConfRef. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTotbl_ConfRef(tbl_ConfRef tbl_ConfRef)
        {
            base.AddObject("tbl_ConfRef", tbl_ConfRef);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet vw_ConfRef. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTovw_ConfRef(vw_ConfRef vw_ConfRef)
        {
            base.AddObject("vw_ConfRef", vw_ConfRef);
        }

        #endregion
    }
    

    #endregion
    
    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExportEtranModel", Name="tbl_Bill")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Bill : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта tbl_Bill.
        /// </summary>
        /// <param name="bill_ID">Исходное значение свойства Bill_ID.</param>
        public static tbl_Bill Createtbl_Bill(global::System.Int32 bill_ID)
        {
            tbl_Bill tbl_Bill = new tbl_Bill();
            tbl_Bill.Bill_ID = bill_ID;
            return tbl_Bill;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Bill_ID
        {
            get
            {
                return _Bill_ID;
            }
            set
            {
                if (_Bill_ID != value)
                {
                    OnBill_IDChanging(value);
                    ReportPropertyChanging("Bill_ID");
                    _Bill_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Bill_ID");
                    OnBill_IDChanged();
                }
            }
        }
        private global::System.Int32 _Bill_ID;
        partial void OnBill_IDChanging(global::System.Int32 value);
        partial void OnBill_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EtranBillID
        {
            get
            {
                return _EtranBillID;
            }
            set
            {
                OnEtranBillIDChanging(value);
                ReportPropertyChanging("EtranBillID");
                _EtranBillID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EtranBillID");
                OnEtranBillIDChanged();
            }
        }
        private Nullable<global::System.Int32> _EtranBillID;
        partial void OnEtranBillIDChanging(Nullable<global::System.Int32> value);
        partial void OnEtranBillIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CarQtty
        {
            get
            {
                return _CarQtty;
            }
            set
            {
                OnCarQttyChanging(value);
                ReportPropertyChanging("CarQtty");
                _CarQtty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarQtty");
                OnCarQttyChanged();
            }
        }
        private Nullable<global::System.Int32> _CarQtty;
        partial void OnCarQttyChanging(Nullable<global::System.Int32> value);
        partial void OnCarQttyChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillNum
        {
            get
            {
                return _BillNum;
            }
            set
            {
                OnBillNumChanging(value);
                ReportPropertyChanging("BillNum");
                _BillNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BillNum");
                OnBillNumChanged();
            }
        }
        private global::System.String _BillNum;
        partial void OnBillNumChanging(global::System.String value);
        partial void OnBillNumChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillState
        {
            get
            {
                return _BillState;
            }
            set
            {
                OnBillStateChanging(value);
                ReportPropertyChanging("BillState");
                _BillState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BillState");
                OnBillStateChanged();
            }
        }
        private global::System.String _BillState;
        partial void OnBillStateChanging(global::System.String value);
        partial void OnBillStateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TakeOverDate
        {
            get
            {
                return _TakeOverDate;
            }
            set
            {
                OnTakeOverDateChanging(value);
                ReportPropertyChanging("TakeOverDate");
                _TakeOverDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TakeOverDate");
                OnTakeOverDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _TakeOverDate;
        partial void OnTakeOverDateChanging(Nullable<global::System.DateTime> value);
        partial void OnTakeOverDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OpenDate
        {
            get
            {
                return _OpenDate;
            }
            set
            {
                OnOpenDateChanging(value);
                ReportPropertyChanging("OpenDate");
                _OpenDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OpenDate");
                OnOpenDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OpenDate;
        partial void OnOpenDateChanging(Nullable<global::System.DateTime> value);
        partial void OnOpenDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ArrivDate
        {
            get
            {
                return _ArrivDate;
            }
            set
            {
                OnArrivDateChanging(value);
                ReportPropertyChanging("ArrivDate");
                _ArrivDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ArrivDate");
                OnArrivDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ArrivDate;
        partial void OnArrivDateChanging(Nullable<global::System.DateTime> value);
        partial void OnArrivDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RaskrDate
        {
            get
            {
                return _RaskrDate;
            }
            set
            {
                OnRaskrDateChanging(value);
                ReportPropertyChanging("RaskrDate");
                _RaskrDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RaskrDate");
                OnRaskrDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _RaskrDate;
        partial void OnRaskrDateChanging(Nullable<global::System.DateTime> value);
        partial void OnRaskrDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DeliveryDate
        {
            get
            {
                return _DeliveryDate;
            }
            set
            {
                OnDeliveryDateChanging(value);
                ReportPropertyChanging("DeliveryDate");
                _DeliveryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeliveryDate");
                OnDeliveryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DeliveryDate;
        partial void OnDeliveryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDeliveryDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RgdOderNum
        {
            get
            {
                return _RgdOderNum;
            }
            set
            {
                OnRgdOderNumChanging(value);
                ReportPropertyChanging("RgdOderNum");
                _RgdOderNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RgdOderNum");
                OnRgdOderNumChanged();
            }
        }
        private Nullable<global::System.Int32> _RgdOderNum;
        partial void OnRgdOderNumChanging(Nullable<global::System.Int32> value);
        partial void OnRgdOderNumChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EtranOderID
        {
            get
            {
                return _EtranOderID;
            }
            set
            {
                OnEtranOderIDChanging(value);
                ReportPropertyChanging("EtranOderID");
                _EtranOderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EtranOderID");
                OnEtranOderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _EtranOderID;
        partial void OnEtranOderIDChanging(Nullable<global::System.Int32> value);
        partial void OnEtranOderIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ConsignorTGNL
        {
            get
            {
                return _ConsignorTGNL;
            }
            set
            {
                OnConsignorTGNLChanging(value);
                ReportPropertyChanging("ConsignorTGNL");
                _ConsignorTGNL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConsignorTGNL");
                OnConsignorTGNLChanged();
            }
        }
        private Nullable<global::System.Int32> _ConsignorTGNL;
        partial void OnConsignorTGNLChanging(Nullable<global::System.Int32> value);
        partial void OnConsignorTGNLChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ConsignorOKPO
        {
            get
            {
                return _ConsignorOKPO;
            }
            set
            {
                OnConsignorOKPOChanging(value);
                ReportPropertyChanging("ConsignorOKPO");
                _ConsignorOKPO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConsignorOKPO");
                OnConsignorOKPOChanged();
            }
        }
        private Nullable<global::System.Int32> _ConsignorOKPO;
        partial void OnConsignorOKPOChanging(Nullable<global::System.Int32> value);
        partial void OnConsignorOKPOChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Consignor
        {
            get
            {
                return _Consignor;
            }
            set
            {
                OnConsignorChanging(value);
                ReportPropertyChanging("Consignor");
                _Consignor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Consignor");
                OnConsignorChanged();
            }
        }
        private global::System.String _Consignor;
        partial void OnConsignorChanging(global::System.String value);
        partial void OnConsignorChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ConsigneeTGNL
        {
            get
            {
                return _ConsigneeTGNL;
            }
            set
            {
                OnConsigneeTGNLChanging(value);
                ReportPropertyChanging("ConsigneeTGNL");
                _ConsigneeTGNL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConsigneeTGNL");
                OnConsigneeTGNLChanged();
            }
        }
        private Nullable<global::System.Int32> _ConsigneeTGNL;
        partial void OnConsigneeTGNLChanging(Nullable<global::System.Int32> value);
        partial void OnConsigneeTGNLChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ConsigneeOKPO
        {
            get
            {
                return _ConsigneeOKPO;
            }
            set
            {
                OnConsigneeOKPOChanging(value);
                ReportPropertyChanging("ConsigneeOKPO");
                _ConsigneeOKPO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConsigneeOKPO");
                OnConsigneeOKPOChanged();
            }
        }
        private Nullable<global::System.Int32> _ConsigneeOKPO;
        partial void OnConsigneeOKPOChanging(Nullable<global::System.Int32> value);
        partial void OnConsigneeOKPOChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Consignee
        {
            get
            {
                return _Consignee;
            }
            set
            {
                OnConsigneeChanging(value);
                ReportPropertyChanging("Consignee");
                _Consignee = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Consignee");
                OnConsigneeChanged();
            }
        }
        private global::System.String _Consignee;
        partial void OnConsigneeChanging(global::System.String value);
        partial void OnConsigneeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DepSt
        {
            get
            {
                return _DepSt;
            }
            set
            {
                OnDepStChanging(value);
                ReportPropertyChanging("DepSt");
                _DepSt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepSt");
                OnDepStChanged();
            }
        }
        private Nullable<global::System.Int32> _DepSt;
        partial void OnDepStChanging(Nullable<global::System.Int32> value);
        partial void OnDepStChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DestSt
        {
            get
            {
                return _DestSt;
            }
            set
            {
                OnDestStChanging(value);
                ReportPropertyChanging("DestSt");
                _DestSt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DestSt");
                OnDestStChanged();
            }
        }
        private Nullable<global::System.Int32> _DestSt;
        partial void OnDestStChanging(Nullable<global::System.Int32> value);
        partial void OnDestStChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PortOKPO
        {
            get
            {
                return _PortOKPO;
            }
            set
            {
                OnPortOKPOChanging(value);
                ReportPropertyChanging("PortOKPO");
                _PortOKPO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PortOKPO");
                OnPortOKPOChanged();
            }
        }
        private Nullable<global::System.Int32> _PortOKPO;
        partial void OnPortOKPOChanging(Nullable<global::System.Int32> value);
        partial void OnPortOKPOChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ETCNG_ID
        {
            get
            {
                return _ETCNG_ID;
            }
            set
            {
                OnETCNG_IDChanging(value);
                ReportPropertyChanging("ETCNG_ID");
                _ETCNG_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ETCNG_ID");
                OnETCNG_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _ETCNG_ID;
        partial void OnETCNG_IDChanging(Nullable<global::System.Int32> value);
        partial void OnETCNG_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private Nullable<global::System.Int32> _Weight;
        partial void OnWeightChanging(Nullable<global::System.Int32> value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CarOwnType_ID
        {
            get
            {
                return _CarOwnType_ID;
            }
            set
            {
                OnCarOwnType_IDChanging(value);
                ReportPropertyChanging("CarOwnType_ID");
                _CarOwnType_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarOwnType_ID");
                OnCarOwnType_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _CarOwnType_ID;
        partial void OnCarOwnType_IDChanging(Nullable<global::System.Int32> value);
        partial void OnCarOwnType_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CarOwnerOKPO
        {
            get
            {
                return _CarOwnerOKPO;
            }
            set
            {
                OnCarOwnerOKPOChanging(value);
                ReportPropertyChanging("CarOwnerOKPO");
                _CarOwnerOKPO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarOwnerOKPO");
                OnCarOwnerOKPOChanged();
            }
        }
        private Nullable<global::System.Int32> _CarOwnerOKPO;
        partial void OnCarOwnerOKPOChanging(Nullable<global::System.Int32> value);
        partial void OnCarOwnerOKPOChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CarOwner
        {
            get
            {
                return _CarOwner;
            }
            set
            {
                OnCarOwnerChanging(value);
                ReportPropertyChanging("CarOwner");
                _CarOwner = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CarOwner");
                OnCarOwnerChanged();
            }
        }
        private global::System.String _CarOwner;
        partial void OnCarOwnerChanging(global::System.String value);
        partial void OnCarOwnerChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DepStELS
        {
            get
            {
                return _DepStELS;
            }
            set
            {
                OnDepStELSChanging(value);
                ReportPropertyChanging("DepStELS");
                _DepStELS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepStELS");
                OnDepStELSChanged();
            }
        }
        private Nullable<global::System.Decimal> _DepStELS;
        partial void OnDepStELSChanging(Nullable<global::System.Decimal> value);
        partial void OnDepStELSChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DepTarif
        {
            get
            {
                return _DepTarif;
            }
            set
            {
                OnDepTarifChanging(value);
                ReportPropertyChanging("DepTarif");
                _DepTarif = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepTarif");
                OnDepTarifChanged();
            }
        }
        private Nullable<global::System.Double> _DepTarif;
        partial void OnDepTarifChanging(Nullable<global::System.Double> value);
        partial void OnDepTarifChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DepNds
        {
            get
            {
                return _DepNds;
            }
            set
            {
                OnDepNdsChanging(value);
                ReportPropertyChanging("DepNds");
                _DepNds = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepNds");
                OnDepNdsChanged();
            }
        }
        private Nullable<global::System.Double> _DepNds;
        partial void OnDepNdsChanging(Nullable<global::System.Double> value);
        partial void OnDepNdsChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DestStELS
        {
            get
            {
                return _DestStELS;
            }
            set
            {
                OnDestStELSChanging(value);
                ReportPropertyChanging("DestStELS");
                _DestStELS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DestStELS");
                OnDestStELSChanged();
            }
        }
        private Nullable<global::System.Decimal> _DestStELS;
        partial void OnDestStELSChanging(Nullable<global::System.Decimal> value);
        partial void OnDestStELSChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DestTarif
        {
            get
            {
                return _DestTarif;
            }
            set
            {
                OnDestTarifChanging(value);
                ReportPropertyChanging("DestTarif");
                _DestTarif = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DestTarif");
                OnDestTarifChanged();
            }
        }
        private Nullable<global::System.Double> _DestTarif;
        partial void OnDestTarifChanging(Nullable<global::System.Double> value);
        partial void OnDestTarifChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DestNds
        {
            get
            {
                return _DestNds;
            }
            set
            {
                OnDestNdsChanging(value);
                ReportPropertyChanging("DestNds");
                _DestNds = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DestNds");
                OnDestNdsChanged();
            }
        }
        private Nullable<global::System.Double> _DestNds;
        partial void OnDestNdsChanging(Nullable<global::System.Double> value);
        partial void OnDestNdsChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Creator
        {
            get
            {
                return _Creator;
            }
            set
            {
                OnCreatorChanging(value);
                ReportPropertyChanging("Creator");
                _Creator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Creator");
                OnCreatorChanged();
            }
        }
        private global::System.String _Creator;
        partial void OnCreatorChanging(global::System.String value);
        partial void OnCreatorChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EditDate
        {
            get
            {
                return _EditDate;
            }
            set
            {
                OnEditDateChanging(value);
                ReportPropertyChanging("EditDate");
                _EditDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EditDate");
                OnEditDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EditDate;
        partial void OnEditDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEditDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Editor
        {
            get
            {
                return _Editor;
            }
            set
            {
                OnEditorChanging(value);
                ReportPropertyChanging("Editor");
                _Editor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Editor");
                OnEditorChanged();
            }
        }
        private global::System.String _Editor;
        partial void OnEditorChanging(global::System.String value);
        partial void OnEditorChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BillCreateDate
        {
            get
            {
                return _BillCreateDate;
            }
            set
            {
                OnBillCreateDateChanging(value);
                ReportPropertyChanging("BillCreateDate");
                _BillCreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BillCreateDate");
                OnBillCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _BillCreateDate;
        partial void OnBillCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnBillCreateDateChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExportEtranModel", "FK_tbl_Bill_tbl_BillCar", "tbl_BillCar")]
        public tbl_BillCar tbl_BillCar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_BillCar>("ExportEtranModel.FK_tbl_Bill_tbl_BillCar", "tbl_BillCar").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_BillCar>("ExportEtranModel.FK_tbl_Bill_tbl_BillCar", "tbl_BillCar").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_BillCar> tbl_BillCarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_BillCar>("ExportEtranModel.FK_tbl_Bill_tbl_BillCar", "tbl_BillCar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_BillCar>("ExportEtranModel.FK_tbl_Bill_tbl_BillCar", "tbl_BillCar", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExportEtranModel", "FK_tbl_BillCar_tbl_Bill", "tbl_BillCar")]
        public EntityCollection<tbl_BillCar> tbl_BillCar_1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_BillCar>("ExportEtranModel.FK_tbl_BillCar_tbl_Bill", "tbl_BillCar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_BillCar>("ExportEtranModel.FK_tbl_BillCar_tbl_Bill", "tbl_BillCar", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExportEtranModel", Name="tbl_BillCar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_BillCar : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта tbl_BillCar.
        /// </summary>
        /// <param name="billCar_ID">Исходное значение свойства BillCar_ID.</param>
        public static tbl_BillCar Createtbl_BillCar(global::System.Int32 billCar_ID)
        {
            tbl_BillCar tbl_BillCar = new tbl_BillCar();
            tbl_BillCar.BillCar_ID = billCar_ID;
            return tbl_BillCar;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BillCar_ID
        {
            get
            {
                return _BillCar_ID;
            }
            set
            {
                if (_BillCar_ID != value)
                {
                    OnBillCar_IDChanging(value);
                    ReportPropertyChanging("BillCar_ID");
                    _BillCar_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BillCar_ID");
                    OnBillCar_IDChanged();
                }
            }
        }
        private global::System.Int32 _BillCar_ID;
        partial void OnBillCar_IDChanging(global::System.Int32 value);
        partial void OnBillCar_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Bill_ID
        {
            get
            {
                return _Bill_ID;
            }
            set
            {
                OnBill_IDChanging(value);
                ReportPropertyChanging("Bill_ID");
                _Bill_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bill_ID");
                OnBill_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Bill_ID;
        partial void OnBill_IDChanging(Nullable<global::System.Int32> value);
        partial void OnBill_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CarNum
        {
            get
            {
                return _CarNum;
            }
            set
            {
                OnCarNumChanging(value);
                ReportPropertyChanging("CarNum");
                _CarNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarNum");
                OnCarNumChanged();
            }
        }
        private Nullable<global::System.Int32> _CarNum;
        partial void OnCarNumChanging(Nullable<global::System.Int32> value);
        partial void OnCarNumChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CarType_ID
        {
            get
            {
                return _CarType_ID;
            }
            set
            {
                OnCarType_IDChanging(value);
                ReportPropertyChanging("CarType_ID");
                _CarType_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarType_ID");
                OnCarType_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _CarType_ID;
        partial void OnCarType_IDChanging(Nullable<global::System.Int32> value);
        partial void OnCarType_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CarWeight
        {
            get
            {
                return _CarWeight;
            }
            set
            {
                OnCarWeightChanging(value);
                ReportPropertyChanging("CarWeight");
                _CarWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarWeight");
                OnCarWeightChanged();
            }
        }
        private Nullable<global::System.Int32> _CarWeight;
        partial void OnCarWeightChanging(Nullable<global::System.Int32> value);
        partial void OnCarWeightChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CarOwnType_ID
        {
            get
            {
                return _CarOwnType_ID;
            }
            set
            {
                OnCarOwnType_IDChanging(value);
                ReportPropertyChanging("CarOwnType_ID");
                _CarOwnType_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarOwnType_ID");
                OnCarOwnType_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _CarOwnType_ID;
        partial void OnCarOwnType_IDChanging(Nullable<global::System.Int32> value);
        partial void OnCarOwnType_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CarOwnerOKPO
        {
            get
            {
                return _CarOwnerOKPO;
            }
            set
            {
                OnCarOwnerOKPOChanging(value);
                ReportPropertyChanging("CarOwnerOKPO");
                _CarOwnerOKPO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarOwnerOKPO");
                OnCarOwnerOKPOChanged();
            }
        }
        private Nullable<global::System.Int32> _CarOwnerOKPO;
        partial void OnCarOwnerOKPOChanging(Nullable<global::System.Int32> value);
        partial void OnCarOwnerOKPOChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CarOwner
        {
            get
            {
                return _CarOwner;
            }
            set
            {
                OnCarOwnerChanging(value);
                ReportPropertyChanging("CarOwner");
                _CarOwner = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CarOwner");
                OnCarOwnerChanged();
            }
        }
        private global::System.String _CarOwner;
        partial void OnCarOwnerChanging(global::System.String value);
        partial void OnCarOwnerChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CarSupplier
        {
            get
            {
                return _CarSupplier;
            }
            set
            {
                OnCarSupplierChanging(value);
                ReportPropertyChanging("CarSupplier");
                _CarSupplier = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarSupplier");
                OnCarSupplierChanged();
            }
        }
        private Nullable<global::System.Int32> _CarSupplier;
        partial void OnCarSupplierChanging(Nullable<global::System.Int32> value);
        partial void OnCarSupplierChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Contract_ID
        {
            get
            {
                return _Contract_ID;
            }
            set
            {
                OnContract_IDChanging(value);
                ReportPropertyChanging("Contract_ID");
                _Contract_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Contract_ID");
                OnContract_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Contract_ID;
        partial void OnContract_IDChanging(Nullable<global::System.Int32> value);
        partial void OnContract_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Customer
        {
            get
            {
                return _Customer;
            }
            set
            {
                OnCustomerChanging(value);
                ReportPropertyChanging("Customer");
                _Customer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Customer");
                OnCustomerChanged();
            }
        }
        private Nullable<global::System.Int32> _Customer;
        partial void OnCustomerChanging(Nullable<global::System.Int32> value);
        partial void OnCustomerChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BranchLine_ID
        {
            get
            {
                return _BranchLine_ID;
            }
            set
            {
                OnBranchLine_IDChanging(value);
                ReportPropertyChanging("BranchLine_ID");
                _BranchLine_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BranchLine_ID");
                OnBranchLine_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _BranchLine_ID;
        partial void OnBranchLine_IDChanging(Nullable<global::System.Int32> value);
        partial void OnBranchLine_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Seller
        {
            get
            {
                return _Seller;
            }
            set
            {
                OnSellerChanging(value);
                ReportPropertyChanging("Seller");
                _Seller = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Seller");
                OnSellerChanged();
            }
        }
        private Nullable<global::System.Int32> _Seller;
        partial void OnSellerChanging(Nullable<global::System.Int32> value);
        partial void OnSellerChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OderCar_ID
        {
            get
            {
                return _OderCar_ID;
            }
            set
            {
                OnOderCar_IDChanging(value);
                ReportPropertyChanging("OderCar_ID");
                _OderCar_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OderCar_ID");
                OnOderCar_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _OderCar_ID;
        partial void OnOderCar_IDChanging(Nullable<global::System.Int32> value);
        partial void OnOderCar_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Resale
        {
            get
            {
                return _Resale;
            }
            set
            {
                OnResaleChanging(value);
                ReportPropertyChanging("Resale");
                _Resale = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Resale");
                OnResaleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Resale;
        partial void OnResaleChanging(Nullable<global::System.Boolean> value);
        partial void OnResaleChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Buyer
        {
            get
            {
                return _Buyer;
            }
            set
            {
                OnBuyerChanging(value);
                ReportPropertyChanging("Buyer");
                _Buyer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Buyer");
                OnBuyerChanged();
            }
        }
        private Nullable<global::System.Int32> _Buyer;
        partial void OnBuyerChanging(Nullable<global::System.Int32> value);
        partial void OnBuyerChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Choice
        {
            get
            {
                return _Choice;
            }
            set
            {
                OnChoiceChanging(value);
                ReportPropertyChanging("Choice");
                _Choice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Choice");
                OnChoiceChanged();
            }
        }
        private Nullable<global::System.Boolean> _Choice;
        partial void OnChoiceChanging(Nullable<global::System.Boolean> value);
        partial void OnChoiceChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Creator
        {
            get
            {
                return _Creator;
            }
            set
            {
                OnCreatorChanging(value);
                ReportPropertyChanging("Creator");
                _Creator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Creator");
                OnCreatorChanged();
            }
        }
        private global::System.String _Creator;
        partial void OnCreatorChanging(global::System.String value);
        partial void OnCreatorChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EditDate
        {
            get
            {
                return _EditDate;
            }
            set
            {
                OnEditDateChanging(value);
                ReportPropertyChanging("EditDate");
                _EditDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EditDate");
                OnEditDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EditDate;
        partial void OnEditDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEditDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Editor
        {
            get
            {
                return _Editor;
            }
            set
            {
                OnEditorChanging(value);
                ReportPropertyChanging("Editor");
                _Editor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Editor");
                OnEditorChanged();
            }
        }
        private global::System.String _Editor;
        partial void OnEditorChanging(global::System.String value);
        partial void OnEditorChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExportEtranModel", "FK_tbl_Bill_tbl_BillCar", "tbl_Bill")]
        public EntityCollection<tbl_Bill> tbl_Bill
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_Bill>("ExportEtranModel.FK_tbl_Bill_tbl_BillCar", "tbl_Bill");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_Bill>("ExportEtranModel.FK_tbl_Bill_tbl_BillCar", "tbl_Bill", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExportEtranModel", "FK_tbl_BillCar_tbl_Bill", "tbl_Bill")]
        public tbl_Bill tbl_Bill_1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Bill>("ExportEtranModel.FK_tbl_BillCar_tbl_Bill", "tbl_Bill").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Bill>("ExportEtranModel.FK_tbl_BillCar_tbl_Bill", "tbl_Bill").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Bill> tbl_Bill_1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Bill>("ExportEtranModel.FK_tbl_BillCar_tbl_Bill", "tbl_Bill");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Bill>("ExportEtranModel.FK_tbl_BillCar_tbl_Bill", "tbl_Bill", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExportEtranModel", Name="tbl_ConfRef")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_ConfRef : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта tbl_ConfRef.
        /// </summary>
        /// <param name="confRef_ID">Исходное значение свойства ConfRef_ID.</param>
        /// <param name="srcTable">Исходное значение свойства SrcTable.</param>
        /// <param name="srcField">Исходное значение свойства SrcField.</param>
        /// <param name="dstTable">Исходное значение свойства DstTable.</param>
        /// <param name="dstField">Исходное значение свойства DstField.</param>
        /// <param name="idField">Исходное значение свойства IdField.</param>
        /// <param name="updateField">Исходное значение свойства UpdateField.</param>
        public static tbl_ConfRef Createtbl_ConfRef(global::System.Int32 confRef_ID, global::System.String srcTable, global::System.String srcField, global::System.String dstTable, global::System.String dstField, global::System.Boolean idField, global::System.Boolean updateField)
        {
            tbl_ConfRef tbl_ConfRef = new tbl_ConfRef();
            tbl_ConfRef.ConfRef_ID = confRef_ID;
            tbl_ConfRef.SrcTable = srcTable;
            tbl_ConfRef.SrcField = srcField;
            tbl_ConfRef.DstTable = dstTable;
            tbl_ConfRef.DstField = dstField;
            tbl_ConfRef.IdField = idField;
            tbl_ConfRef.UpdateField = updateField;
            return tbl_ConfRef;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConfRef_ID
        {
            get
            {
                return _ConfRef_ID;
            }
            set
            {
                if (_ConfRef_ID != value)
                {
                    OnConfRef_IDChanging(value);
                    ReportPropertyChanging("ConfRef_ID");
                    _ConfRef_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ConfRef_ID");
                    OnConfRef_IDChanged();
                }
            }
        }
        private global::System.Int32 _ConfRef_ID;
        partial void OnConfRef_IDChanging(global::System.Int32 value);
        partial void OnConfRef_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SrcTable
        {
            get
            {
                return _SrcTable;
            }
            set
            {
                OnSrcTableChanging(value);
                ReportPropertyChanging("SrcTable");
                _SrcTable = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SrcTable");
                OnSrcTableChanged();
            }
        }
        private global::System.String _SrcTable;
        partial void OnSrcTableChanging(global::System.String value);
        partial void OnSrcTableChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SrcField
        {
            get
            {
                return _SrcField;
            }
            set
            {
                OnSrcFieldChanging(value);
                ReportPropertyChanging("SrcField");
                _SrcField = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SrcField");
                OnSrcFieldChanged();
            }
        }
        private global::System.String _SrcField;
        partial void OnSrcFieldChanging(global::System.String value);
        partial void OnSrcFieldChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DstTable
        {
            get
            {
                return _DstTable;
            }
            set
            {
                OnDstTableChanging(value);
                ReportPropertyChanging("DstTable");
                _DstTable = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DstTable");
                OnDstTableChanged();
            }
        }
        private global::System.String _DstTable;
        partial void OnDstTableChanging(global::System.String value);
        partial void OnDstTableChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
		[DataMemberAttribute()]
        public global::System.String DstField
        {
            get
            {
                return _DstField;
            }
            set
            {
				if(string.IsNullOrEmpty(value)) return;

				OnDstFieldChanging(value);
				ReportPropertyChanging("DstField");
				_DstField = StructuralObject.SetValidValue(value, false);
				ReportPropertyChanged("DstField");
				OnDstFieldChanged();
            }
        }
        private global::System.String _DstField;
        partial void OnDstFieldChanging(global::System.String value);
        partial void OnDstFieldChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IdField
        {
            get
            {
                return _IdField;
            }
            set
            {
                OnIdFieldChanging(value);
                ReportPropertyChanging("IdField");
                _IdField = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdField");
                OnIdFieldChanged();
            }
        }
        private global::System.Boolean _IdField;
        partial void OnIdFieldChanging(global::System.Boolean value);
        partial void OnIdFieldChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean UpdateField
        {
            get
            {
                return _UpdateField;
            }
            set
            {
                OnUpdateFieldChanging(value);
                ReportPropertyChanging("UpdateField");
                _UpdateField = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateField");
                OnUpdateFieldChanged();
            }
        }
        private global::System.Boolean _UpdateField;
        partial void OnUpdateFieldChanging(global::System.Boolean value);
        partial void OnUpdateFieldChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ParentTable
        {
            get
            {
                return _ParentTable;
            }
            set
            {
                OnParentTableChanging(value);
                ReportPropertyChanging("ParentTable");
                _ParentTable = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ParentTable");
                OnParentTableChanged();
            }
        }
        private global::System.String _ParentTable;
        partial void OnParentTableChanging(global::System.String value);
        partial void OnParentTableChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> ActualField
        {
            get
            {
                return _ActualField;
            }
            set
            {
                OnActualFieldChanging(value);
                ReportPropertyChanging("ActualField");
                _ActualField = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActualField");
                OnActualFieldChanged();
            }
        }
        private Nullable<global::System.Byte> _ActualField;
        partial void OnActualFieldChanging(Nullable<global::System.Byte> value);
        partial void OnActualFieldChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CostName2_ID
        {
            get
            {
                return _CostName2_ID;
            }
            set
            {
                OnCostName2_IDChanging(value);
                ReportPropertyChanging("CostName2_ID");
                _CostName2_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostName2_ID");
                OnCostName2_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _CostName2_ID;
        partial void OnCostName2_IDChanging(Nullable<global::System.Int32> value);
        partial void OnCostName2_IDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExportEtranModel", Name="vw_ConfRef")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_ConfRef : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта vw_ConfRef.
        /// </summary>
        /// <param name="confRef_ID">Исходное значение свойства ConfRef_ID.</param>
        /// <param name="srcTable">Исходное значение свойства SrcTable.</param>
        /// <param name="srcField">Исходное значение свойства SrcField.</param>
        /// <param name="dstTable">Исходное значение свойства DstTable.</param>
        /// <param name="dstField">Исходное значение свойства DstField.</param>
        /// <param name="idField">Исходное значение свойства IdField.</param>
        /// <param name="updateField">Исходное значение свойства UpdateField.</param>
        public static vw_ConfRef Createvw_ConfRef(global::System.Int32 confRef_ID, global::System.String srcTable, global::System.String srcField, global::System.String dstTable, global::System.String dstField, global::System.Boolean idField, global::System.Boolean updateField)
        {
            vw_ConfRef vw_ConfRef = new vw_ConfRef();
            vw_ConfRef.ConfRef_ID = confRef_ID;
            vw_ConfRef.SrcTable = srcTable;
            vw_ConfRef.SrcField = srcField;
            vw_ConfRef.DstTable = dstTable;
            vw_ConfRef.DstField = dstField;
            vw_ConfRef.IdField = idField;
            vw_ConfRef.UpdateField = updateField;
            return vw_ConfRef;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConfRef_ID
        {
            get
            {
                return _ConfRef_ID;
            }
            set
            {
                if (_ConfRef_ID != value)
                {
                    OnConfRef_IDChanging(value);
                    ReportPropertyChanging("ConfRef_ID");
                    _ConfRef_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ConfRef_ID");
                    OnConfRef_IDChanged();
                }
            }
        }
        private global::System.Int32 _ConfRef_ID;
        partial void OnConfRef_IDChanging(global::System.Int32 value);
        partial void OnConfRef_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SrcTable
        {
            get
            {
                return _SrcTable;
            }
            set
            {
                OnSrcTableChanging(value);
                ReportPropertyChanging("SrcTable");
                _SrcTable = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SrcTable");
                OnSrcTableChanged();
            }
        }
        private global::System.String _SrcTable;
        partial void OnSrcTableChanging(global::System.String value);
        partial void OnSrcTableChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SrcField
        {
            get
            {
                return _SrcField;
            }
            set
            {
                OnSrcFieldChanging(value);
                ReportPropertyChanging("SrcField");
                _SrcField = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SrcField");
                OnSrcFieldChanged();
            }
        }
        private global::System.String _SrcField;
        partial void OnSrcFieldChanging(global::System.String value);
        partial void OnSrcFieldChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DstTable
        {
            get
            {
                return _DstTable;
            }
            set
            {
                OnDstTableChanging(value);
                ReportPropertyChanging("DstTable");
                _DstTable = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DstTable");
                OnDstTableChanged();
            }
        }
        private global::System.String _DstTable;
        partial void OnDstTableChanging(global::System.String value);
        partial void OnDstTableChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DstField
        {
            get
            {
                return _DstField;
            }
            set
            {
                OnDstFieldChanging(value);
                ReportPropertyChanging("DstField");
                _DstField = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DstField");
                OnDstFieldChanged();
            }
        }
        private global::System.String _DstField;
        partial void OnDstFieldChanging(global::System.String value);
        partial void OnDstFieldChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ParentTable
        {
            get
            {
                return _ParentTable;
            }
            set
            {
                OnParentTableChanging(value);
                ReportPropertyChanging("ParentTable");
                _ParentTable = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ParentTable");
                OnParentTableChanged();
            }
        }
        private global::System.String _ParentTable;
        partial void OnParentTableChanging(global::System.String value);
        partial void OnParentTableChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IdField
        {
            get
            {
                return _IdField;
            }
            set
            {
                OnIdFieldChanging(value);
                ReportPropertyChanging("IdField");
                _IdField = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdField");
                OnIdFieldChanged();
            }
        }
        private global::System.Boolean _IdField;
        partial void OnIdFieldChanging(global::System.Boolean value);
        partial void OnIdFieldChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean UpdateField
        {
            get
            {
                return _UpdateField;
            }
            set
            {
                OnUpdateFieldChanging(value);
                ReportPropertyChanging("UpdateField");
                _UpdateField = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateField");
                OnUpdateFieldChanged();
            }
        }
        private global::System.Boolean _UpdateField;
        partial void OnUpdateFieldChanging(global::System.Boolean value);
        partial void OnUpdateFieldChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> ActualField
        {
            get
            {
                return _ActualField;
            }
            set
            {
                OnActualFieldChanging(value);
                ReportPropertyChanging("ActualField");
                _ActualField = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActualField");
                OnActualFieldChanged();
            }
        }
        private Nullable<global::System.Byte> _ActualField;
        partial void OnActualFieldChanging(Nullable<global::System.Byte> value);
        partial void OnActualFieldChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CostName2_ID
        {
            get
            {
                return _CostName2_ID;
            }
            set
            {
                OnCostName2_IDChanging(value);
                ReportPropertyChanging("CostName2_ID");
                _CostName2_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostName2_ID");
                OnCostName2_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _CostName2_ID;
        partial void OnCostName2_IDChanging(Nullable<global::System.Int32> value);
        partial void OnCostName2_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CostName
        {
            get
            {
                return _CostName;
            }
            set
            {
                OnCostNameChanging(value);
                ReportPropertyChanging("CostName");
                _CostName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CostName");
                OnCostNameChanged();
            }
        }
        private global::System.String _CostName;
        partial void OnCostNameChanging(global::System.String value);
        partial void OnCostNameChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ExportEtranModel", Name="ComplexType1")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ComplexType1 : ComplexObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта ComplexType1.
        /// </summary>
        /// <param name="cost">Исходное значение свойства cost.</param>
        public static ComplexType1 CreateComplexType1(global::System.String cost)
        {
            ComplexType1 complexType1 = new ComplexType1();
            complexType1.cost = cost;
            return complexType1;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cost
        {
            get
            {
                return _cost;
            }
            set
            {
                OncostChanging(value);
                ReportPropertyChanging("cost");
                _cost = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cost");
                OncostChanged();
            }
        }
        private global::System.String _cost;
        partial void OncostChanging(global::System.String value);
        partial void OncostChanged();

        #endregion
    }

    #endregion
    
}